variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(80846640-c6ce-4d33-aa12-c45dcd84edac)'
    appType: 'webAppLinux'
    appName: 'restfulorders'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|7.0'