@CSharp_HostAddress = http://localhost:5070

### CREATE ORDER
POST {{CSharp_HostAddress}}/Order
Content-Type: application/json

{
  "email": "httpTest2@testmail.com"
}
> {%
    client.global.set("order_guid", response.body["id"]);
    client.global.set("customer_guid", response.body["customerId"]);
    client.log(response.body["id"]);
    client.log(client.global.get("id"));
%}

### GETALL ORDERS
GET {{CSharp_HostAddress}}/Order
Accept: application/json

### GET ORDER
GET {{CSharp_HostAddress}}/Order/{{order_guid}}
Accept: application/jsonGET

### UPDATE ORDER
PUT {{CSharp_HostAddress}}/Order/{{order_guid}}
Content-Type: application/json

{
  "id": "{{order_guid}}",
  "createdDate" : "1922-05-15T18:17:48.782503",
  "customerId" : "{{customer_guid}}"
}

### CREATE ORDER FOR ANOTHER CUSTOMER
POST {{CSharp_HostAddress}}/Order
Content-Type: application/json

{
  "email": "httpTestnew@testmail.com"
}
> {%
    client.global.set("order_guid", response.body["id"]);
    client.global.set("customer_guid", response.body["customerId"]);
    client.log(response.body["id"]);
    client.log(client.global.get("id"));
%}


### GETALL CUSTOMERS
GET {{CSharp_HostAddress}}/Customer
Accept: application/json

### GET CUSTOMER
GET {{CSharp_HostAddress}}/Customer/{{customer_guid}}
Accept: application/json

### GET ALL ORDERS BY CUSTOMER
GET {{CSharp_HostAddress}}/Order/Customer/{{customer_guid}}
Accept: application/json

### DELETE ORDER
DELETE {{CSharp_HostAddress}}/Order/{{order_guid}}