@CSharp_HostAddress = http://localhost:5070

### CREATE
POST {{CSharp_HostAddress}}/Order
Content-Type: application/json

{
  "email": "httpTest2@testmail.com"
}
> {%
    client.global.set("order_guid", response.body["id"]);
    client.global.set("customer_guid", response.body["customerId"]);
    client.log(response.body["id"]);
    client.log(client.global.get("id"));

%}

### GETALL
GET {{CSharp_HostAddress}}/Order
Accept: application/json

### GET
GET {{CSharp_HostAddress}}/Order/{{order_guid}}
Accept: application/jsonGET

### UPDATE
PUT {{CSharp_HostAddress}}/Order/{{order_guid}}
Content-Type: application/json

{
  "id": "{{order_guid}}",
  "createdDate" : "1922-05-15T18:17:48.782503",
  "customerId" : "{{customer_guid}}"
}

### DELETE
DELETE {{CSharp_HostAddress}}/Order/{{order_guid}}